apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanzu-app
  labels:
    app: tanzu-app
spec:
  rules:
  - host: {{session_namespace}}-app.{{ingress_domain}}
    http:
      paths:
      - path: "/api"
        pathType: Prefix
        backend:
          service:
            name: spring-api
            port:
              number: 8080
