---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-2
  labels:
    component: spring-api-2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spring-api-2
  template:
    metadata:
      labels:
        component: spring-api-2
    spec:
      containers:
      - name: spring-api-2
        image: <spring-api-2-image>
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
